title: Slab appinsights
description: Main-development-repository-for-Application-Insights-integration-with-Semantic-logging
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
